### ISSUE TITLE
node_package failing

### ISSUE THREAD

**Issue by freebrevik** [poise/application_javascript#1]
I keep getting this error with node_package trying to install pm2:

```
> Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of ["/opt/nodejs-6.9.1/bin/node", "/opt/nodejs-6.9.1/bin/npm", "list", "--json", "--depth", "0"] ----
STDOUT: 
STDERR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:183:in `chdir': No such file or directory @ dir_chdir - grunt-cli (Errno::ENOENT)
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:183:in `set_cwd'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:335:in `block in fork_subprocess'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork_subprocess'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:93:in `run_command'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:259:in `run_command'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/mixin/shell_out.rb:86:in `shell_out_command'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/mixin/shell_out.rb:39:in `shell_out'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:78:in `poise_shell_out'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:197:in `language_command_shell_out'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:217:in `block in language_command_mixin'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:207:in `language_command_shell_out!'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:222:in `block in language_command_mixin'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-javascript/files/halite_gem/poise_javascript/resources/node_package.rb:213:in `npm_shell_out!'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-javascript/files/halite_gem/poise_javascript/resources/node_package.rb:120:in `check_package_versions'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-javascript/files/halite_gem/poise_javascript/resources/node_package.rb:106:in `load_current_resource'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/provider.rb:128:in `run_action'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource.rb:603:in `run_action'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
from /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
from /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:669:in `block in converge'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:664:in `catch'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:664:in `converge'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:703:in `converge_and_save'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:283:in `run'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:302:in `block in fork_chef_client'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:290:in `fork'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:290:in `fork_chef_client'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:255:in `block in run_chef_client'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:243:in `run_chef_client'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:450:in `loop'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:450:in `interval_run_chef_client'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:434:in `run_application'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:60:in `run'
from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/bin/chef-client:26:in `<top (required)>'
from /opt/chef/bin/chef-client:53:in `load'
from /opt/chef/bin/chef-client:53:in `<main>'
---- End output of ["/opt/nodejs-6.9.1/bin/node", "/opt/nodejs-6.9.1/bin/npm", "list", "--json", "--depth", "0"] ----
Ran ["/opt/nodejs-6.9.1/bin/node", "/opt/nodejs-6.9.1/bin/npm", "list", "--json", "--depth", "0"] returned 1
 ```

**Comment by coderanger** [comment]
Please include your recipe code. This sounds like you requested a working directory that does not exist.

**Comment by freebrevik** [comment]
``` ruby
include_recipe 'aws'

app = search(:aws_opsworks_app).first
app_path = "/srv/#{app['shortname']}"

package "git" do
  options "--force-yes" if node["platform"] == "ubuntu" && node["platform_version"] == "14.04"
end

application app_path do

  javascript app_path do
    version "6.9.1"
    options :system, dev_package: false
  end

  environment.update("PORT" => "80")
  environment.update(app["environment"])

  git app_path do
    repository app["app_source"]["url"]
    deploy_key app['app_source']['ssh_key']
    #revision app["app_source"]["revision"]
  end

  node_package 'pm2'

  npm_install

  npm_start do
    action [:stop, :enable, :start]
  end


end
```

**Comment by freebrevik** [comment]
Everything else works, only adding this node_package fails. The Application Path is /srv/app_name/ where the app resides. Other than that there isn't anything else going on here really.

**Comment by coderanger** [comment]
What's the resource detail view in the error trace show?

**Comment by freebrevik** [comment]
Here I'm trying grunt instead but same thing (I'm assuming this is what you meant):

```
Cookbook Trace:
---------------
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:207:in `tap'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:207:in `language_command_shell_out!'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:222:in `block in language_command_mixin'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-javascript/files/halite_gem/poise_javascript/resources/node_package.rb:213:in `npm_shell_out!'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-javascript/files/halite_gem/poise_javascript/resources/node_package.rb:120:in `check_package_versions'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/poise-javascript/files/halite_gem/poise_javascript/resources/node_package.rb:106:in `load_current_resource'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Resource Declaration:
---------------------
# In /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/test_cookbook/recipes/default.rb

62:   node_package 'grunt-cli'
63: 

Compiled Resource:
------------------
# Declared in /var/chef/runs/7d8e4138-7858-430f-98f8-6f243c173242/local-mode-cache/cache/cookbooks/test_cookbook/recipes/default.rb:62:in `block in from_file'

application_node_package("grunt-cli") do
package_name "grunt-cli"
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :application_node_package
cookbook_name "test_cookbook"
recipe_name "default"
parent application[/srv/nodejs_sample_app]
parent_javascript application_javascript[/srv/nodejs_sample_app]
npm_binary "/opt/nodejs-6.9.1/bin/npm"
timeout 900
path "grunt-cli"
end
```

**Comment by coderanger** [comment]
Please report a single case or I can't tell what is going on. What is the error you get from the code you posted earlier?

**Comment by freebrevik** [comment]
> Expected process to exit with [0], but received '1'
> ---- Begin output of ["/opt/nodejs-6.9.1/bin/node", "/opt/nodejs-6.9.1/bin/npm", "list", "--json", "--depth", "0"] ----
> STDOUT:
> STDERR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:183:in chdir': No such file or directory @ dir_chdir - grunt-cli

**Comment by coderanger** [comment]
Just to be clear, you're saying you see the error referencing `grunt-cli` even though your recipe only mentioned `pm2`? Because that would be really quite weird.

**Comment by freebrevik** [comment]
No sorry, I originally was trying pm2, but then experimented with grunt-cli just to make sure it wasn't anything to do with the package I was trying! Either way it resulted in the same error.

**Comment by coderanger** [comment]
Please give me the error and code as they stand currently. This is what I mean about I need to know what case you are describing.

**Comment by coderanger** [comment]
Closing this out until a consistent error and recipe code is available.
